[ROCm] Skip failing hipsparselt unit tests (#178355)
Skipping the following 12 unit tests because they fail due to hipSPARSELt implementation issues on ROCm, which are still under development.

```
ERROR: test_cslt_sparse_mm_search_cuda_bfloat16 (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_cslt_sparse_mm_search_cuda_bfloat16)
ERROR: test_cslt_sparse_mm_search_cuda_float16 (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_cslt_sparse_mm_search_cuda_float16)
ERROR: test_cslt_sparse_mm_search_cuda_int8 (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_cslt_sparse_mm_search_cuda_int8)
ERROR: test_csrc_cslt_sparse_mm_search_cuda_bfloat16 (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_csrc_cslt_sparse_mm_search_cuda_bfloat16)
ERROR: test_csrc_cslt_sparse_mm_search_cuda_float16 (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_csrc_cslt_sparse_mm_search_cuda_float16)
ERROR: test_csrc_cslt_sparse_mm_search_cuda_int8 (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_csrc_cslt_sparse_mm_search_cuda_int8)
ERROR: test_cusparselt_backend_cuda (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_cusparselt_backend_cuda)
ERROR: test_sparse_fp8fp8_mm_dense_input_shape0_cuda (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_sparse_fp8fp8_mm_dense_input_shape0_cuda)
ERROR: test_sparse_semi_structured_scaled_mm_bfloat16_dense_input_shape0_cuda (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_sparse_semi_structured_scaled_mm_bfloat16_dense_input_shape0_cuda)
ERROR: test_sparse_semi_structured_scaled_mm_float16_dense_input_shape0_cuda (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_sparse_semi_structured_scaled_mm_float16_dense_input_shape0_cuda)
ERROR: test_sparse_semi_structured_scaled_mm_float32_dense_input_shape0_cuda (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_sparse_semi_structured_scaled_mm_float32_dense_input_shape0_cuda)
ERROR: test_sparse_semi_structured_scaled_mm_fp8_cuda (__main__.TestSparseSemiStructuredCUSPARSELTCUDA.test_sparse_semi_structured_scaled_mm_fp8_cuda)

```
These failures occur after enabling `torch.backends.cusparselt.is_available()` on ROCm via https://github.com/pytorch/pytorch/pull/178285

Pull Request resolved: https://github.com/pytorch/pytorch/pull/178355
Approved by: https://github.com/jeffdaily