[Python 3.14] Bump flake8-simplify version (#182160)
Fixes https://github.com/pytorch/pytorch/issues/182158

Python 3.14 removes legacy AST node classes (`ast.Str`, `ast.Num`, `ast.NameConstant`, etc.) that were deprecated since Python 3.8 and replaced by `ast.Constant` (see [Python 3.14 docs)](https://docs.python.org/3.14/deprecations/pending-removal-in-3.14.html).

This affects astor used by flake8-simplify for AST, so invoking lintrunner on flake8 will throw
```Python
AttributeError: module 'ast' has no attribute 'Str'
```

As linters in PyTorch are running in ephemeral uv venvs, it can be easily fixed by bumping flake8-simplify package to 0.30.0.
Pull Request resolved: https://github.com/pytorch/pytorch/pull/182160
Approved by: https://github.com/malfet