Revert "Remove TorchVitals (#178479)"
This reverts commit 179e2d57a9ed44b0d930f688430480c899da4c49.

Reverted https://github.com/pytorch/pytorch/pull/178479 on behalf of https://github.com/georgehong due to change is breaking internal tests: AttributeError: module 'torch' has no attribute 'set_vital' ([comment](https://github.com/pytorch/pytorch/pull/178479#issuecomment-4145885127))